[2021-04-20 07:05:21,875] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: global_dag.create_tables 2018-11-01T00:00:00+00:00 [queued]>
[2021-04-20 07:05:21,907] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: global_dag.create_tables 2018-11-01T00:00:00+00:00 [queued]>
[2021-04-20 07:05:21,908] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2021-04-20 07:05:21,909] {taskinstance.py:867} INFO - Starting attempt 2 of 4
[2021-04-20 07:05:21,911] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2021-04-20 07:05:21,974] {taskinstance.py:887} INFO - Executing <Task(PostgresOperator): create_tables> on 2018-11-01T00:00:00+00:00
[2021-04-20 07:05:21,979] {standard_task_runner.py:53} INFO - Started process 3354 to run task
[2021-04-20 07:05:22,077] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: global_dag.create_tables 2018-11-01T00:00:00+00:00 [running]> 68b6afff5d68
[2021-04-20 07:05:22,105] {postgres_operator.py:62} INFO - Executing: CREATE TABLE IF NOT EXISTS public.staging_sales (
	City varchar(256),
	Brand varchar(256),
	Ads numeric(18,0),
	Region varchar(256),
	Location varchar(256),
	Nb_cash_register int4,
	Population int4,
	Blue_collar_rate numeric(18,0),
	White_collar_rate numeric(18,0),
	Jobless_rate numeric(18,0),
	Lt_25_yo numeric(18,0),
	25_35_yo numeric(18,0),
	gt_35_yo numeric(18,0)
);




CREATE TABLE IF NOT EXISTS public.staging_songs (
	num_songs int4,
	artist_id varchar(256),
	artist_name varchar(256),
	artist_latitude numeric(18,0),
	artist_longitude numeric(18,0),
	artist_location varchar(256),
	song_id varchar(256),
	title varchar(256),
	duration numeric(18,0),
	"year" int4
);


CREATE TABLE IF NOT EXISTS public.artists (
	artistid varchar(256) NOT NULL,
	name varchar(256),
	location varchar(256),
	lattitude numeric(18,0),
	longitude numeric(18,0)
);

CREATE TABLE IF NOT EXISTS public.songplays (
	playid varchar(32) NOT NULL,
	start_time timestamp NOT NULL,
	userid int4 NOT NULL,
	"level" varchar(256),
	songid varchar(256),
	artistid varchar(256),
	sessionid int4,
	location varchar(256),
	user_agent varchar(256),
	CONSTRAINT songplays_pkey PRIMARY KEY (playid)
);

CREATE TABLE IF NOT EXISTS public.songs (
	songid varchar(256) NOT NULL,
	title varchar(256),
	artistid varchar(256),
	"year" int4,
	duration numeric(18,0),
	CONSTRAINT songs_pkey PRIMARY KEY (songid)
);


CREATE TABLE IF NOT EXISTS public."time" (
	start_time timestamp NOT NULL,
	"hour" int4,
	"day" int4,
	week int4,
	"month" varchar(256),
	"year" int4,
	weekday varchar(256),
	CONSTRAINT time_pkey PRIMARY KEY (start_time)
);

CREATE TABLE IF NOT EXISTS public.users (
	userid int4 NOT NULL,
	first_name varchar(256),
	last_name varchar(256),
	gender varchar(256),
	"level" varchar(256),
	CONSTRAINT users_pkey PRIMARY KEY (userid)
);





[2021-04-20 07:05:22,125] {taskinstance.py:1128} ERROR - The conn_id `redshift` isn't defined
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python3.7/site-packages/airflow/operators/postgres_operator.py", line 65, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/dbapi_hook.py", line 162, in run
    with closing(self.get_conn()) as conn:
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/postgres_hook.py", line 71, in get_conn
    conn = self.get_connection(conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 81, in get_connection
    conn = random.choice(list(cls.get_connections(conn_id)))
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 76, in get_connections
    conns = cls._get_connections_from_db(conn_id)
  File "/usr/local/lib/python3.7/site-packages/airflow/utils/db.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/airflow/hooks/base_hook.py", line 59, in _get_connections_from_db
    "The conn_id `{0}` isn't defined".format(conn_id))
airflow.exceptions.AirflowException: The conn_id `redshift` isn't defined
[2021-04-20 07:05:22,128] {taskinstance.py:1151} INFO - Marking task as UP_FOR_RETRY
[2021-04-20 07:05:31,787] {logging_mixin.py:112} INFO - [2021-04-20 07:05:31,787] {local_task_job.py:103} INFO - Task exited with return code 1
