[2021-04-20 07:07:40,360] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: global_dag.upload_file 2018-11-01T00:00:00+00:00 [queued]>
[2021-04-20 07:07:40,391] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: global_dag.upload_file 2018-11-01T00:00:00+00:00 [queued]>
[2021-04-20 07:07:40,392] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2021-04-20 07:07:40,393] {taskinstance.py:867} INFO - Starting attempt 2 of 4
[2021-04-20 07:07:40,394] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2021-04-20 07:07:40,447] {taskinstance.py:887} INFO - Executing <Task(UploadFileOperator): upload_file> on 2018-11-01T00:00:00+00:00
[2021-04-20 07:07:40,451] {standard_task_runner.py:53} INFO - Started process 3453 to run task
[2021-04-20 07:07:40,547] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: global_dag.upload_file 2018-11-01T00:00:00+00:00 [running]> 68b6afff5d68
[2021-04-20 07:07:40,602] {upload_file.py:61} INFO - Uploading file to S3.
[2021-04-20 07:07:43,639] {taskinstance.py:1048} INFO - Marking task as SUCCESS.dag_id=global_dag, task_id=upload_file, execution_date=20181101T000000, start_date=20210420T070740, end_date=20210420T070743
[2021-04-20 07:07:50,328] {logging_mixin.py:112} INFO - [2021-04-20 07:07:50,328] {local_task_job.py:103} INFO - Task exited with return code 0
